name: Restrict merges to main


on:
 push:
   branches:
     - main
 pull_request:
   branches:
     - main
     
defaults:
  run:
    shell: pwsh


jobs:
 restrict-to-merge-branch-main:
   runs-on: ubuntu-latest 


   steps:
     - name: Check merge branch
       run: |
        if ("${{ github.event.pull_request.head.ref }}" -eq 'main' -or ("${{ github.event_name }}" -eq 'push' -and "${{ github.ref }}" -eq 'refs/heads/main')) {
          if ( -not "${{ github.event.pull_request.head.ref }}".StartsWith("release/")) {
            throw "Merges to main are only allowed from the release/* branch."
          }
          if ( "${{ github.event_name }}" -eq 'push' ) {
            throw "Pushes to main are allowed only in PRs from the release/* branch."
          }
        }
