name: Restrict pr merges to release 

on:
 push:
   branches:
    - release
 pull_request:
   branches:
     - release

defaults:
  run:
    shell: pwsh

jobs:
 restrict-to-merge-branch-release:
   runs-on: ubuntu-latest


   steps:

     - name: Check merge branch
       run: |
        if (( -not "${{ github.event.pull_request.head.ref }}".StartsWith("hotfix/")) -or ( -not "${{ github.event.pull_request.head.ref }}".StartsWith("bugfix/"))) {
          throw "Merges to release are only allowed from a hotfix/* or a bugfix/* branch."
        }
      
