name: Restrict push merges to develop

on:
 push:
   branches:
    - develop
 pull_request:
   branches:
     - develop

defaults:
  run:
    shell: pwsh

jobs:
 restrict-push-to-merge-branch-develop:
   runs-on: ubuntu-latest


   steps:

     - name: Check merge branch
       run: |
        write-host "Checking if the push is from the main branch post release."
        write-host "Current ref: "${{ github.ref }}
        
        if ( "${{ github.ref }}".StartsWith("refs/heads/main")) {
          throw "Pushes to develop are allowed only from the main branch post release."
        }
        write-host "Push is valid."

