name: Restrict merges to develop 

on:
 push:
   branches:
    - develop
 pull_request:
   branches:
     - develop

defaults:
  run:
    shell: pwsh

jobs:
 restrict-to-merge-branch-develop:
   runs-on: ubuntu-latest


   steps:

     - name: Check merge branch
       run: |
        if ("${{ github.event.pull_request.base.ref }}" -eq 'develop') {
          if ( "${{ github.event_name }}" -eq 'pull_request' -and -not "${{ github.event.pull_request.head.ref }}".StartsWith("feature/")) {
            throw "Merges to develop are only allowed from the feature/* branch."
          }
        }
        if ( "${{ github.event_name }}" -eq 'push' ) {
          if ( -not "${{ github.ref }}".StartsWith("refs/heads/main") ) {
            throw "Pushes to develop are allowed only in PRs from the feature/* branch or from the main branch post release."
          }
        }
